apiVersion: v1
kind: Service
metadata:
  name: kandula-service-loadbalancer
spec:
  selector:
    app: opsschool-app-evgy
  type: LoadBalancer
  ports:
    - name: http
      port: 5000 
      targetPort: 5000 
      # nodePort: 30036 #--> The Service "kandula-service-loadbalancer" is invalid: spec.ports[0].nodePort: Invalid value: 30036: provided port is already allocated
      protocol: TCP