apiVersion: apps/v1
kind: Deployment
metadata:
  name: opsschool-app-evgy
  annotations:
    kubernetes.io/change-cause: "First release kuard-amd64:1"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: opsschool-app-evgy
  template:
    metadata:
      labels:
        app: opsschool-app-evgy
    spec:
      containers:
      - name: opsschool-app-evgy
        image: jekat/kandula:latest
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
        # livenessProbe:
        #  httpGet:
        #    path: /healthy
        #    port: 8080
        #  initialDelaySeconds: 10
        #  timeoutSeconds: 1
        #  periodSeconds: 10
        #  failureThreshold: 3 
---
apiVersion: v1
kind: Service
metadata:
  name: opsschool-service-evgy
spec:
  selector:
    app: opsschool-app-evgy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000           